;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
;; This file is auto generated. Do not edit this file. All changes must be made in config.org

(setq doom-font (font-spec :family "FiraCode Nerd Font" :size 18 :weight 'medium)
     doom-variable-pitch-font (font-spec :family "FiraCode Nerd Font" :size 18)
      doom-symbol-font (font-spec :family "FiraCode Nerd Font" :size 18)
      doom-serif-font (font-spec :family "FiraCode Nerd Font" :size 18))

;; Set background transparency to 85%
(set-frame-parameter nil 'alpha-background 85)
(add-to-list 'default-frame-alist '(alpha-background . 85))

(setq org-directory "~/org/")


(custom-set-faces!
  `(org-level-1 :family "Luminari" :height 400)
  `(org-level-2 :family "Cochin" :height 300)
  `(org-level-3 :family "Rockwell" :height 200)
  `(org-level-4 :family "Rockwell" :height 150)
  `(org-level-5 :family "Rockwell" :height 150)
  `(org-level-6 :family "Rockwell" :height 150)
                )

(defun my/org-format-code-block ()
  "Format code block at point by opening special edit buffer, formatting, and returning."
  (interactive)
  (if (org-in-src-block-p)
      (progn
        (org-edit-special)
        ;; Use Doom's format function
        (+format/region-or-buffer)
        ;; Return to org buffer
        (org-edit-src-exit))
    (message "Not in an org source block")))

;; Bind to leader c b
(map! :leader
      :desc "Format org code block" "c b" #'my/org-format-code-block)

(setq projectile-enable-caching nil)

;; Add themes directory to load path
(add-to-list 'custom-theme-load-path (expand-file-name "themes" doom-user-dir))

(setq catppuccin-flavor 'latte)

(setq display-line-numbers-type t)
(setq-default tab-width 2)
(global-visual-line-mode 1)
(if (display-graphic-p)
    (progn
      (setq initial-frame-alist
            '((tool-bar-lines . 0)
              (width . 200)
              (height . 400)
              )
            )
      )
  )

(add-function :after after-focus-change-function
  (lambda ()
    (save-some-buffers t)))

(setq undo-limit 80000000
      evil-want-fine-undo t
      auto-save-default t)

(global-subword-mode t)

(map! :leader
      :desc "Quit Emacs" "h Q" #'save-buffers-kill-emacs)

(after! evil
  (setq evil-kill-on-visual-paste t))

;; Use yq for YAML formatting instead of prettier
(after! apheleia
  (setf (alist-get 'yaml-mode apheleia-mode-alist) 'yq-yaml)
  (setf (alist-get 'yaml-ts-mode apheleia-mode-alist) 'yq-yaml))

(use-package! inheritenv
  :config
  ;; Add advice to core commands that need environment inheritance
  (inheritenv-add-advice 'shell-command-to-string)
  (inheritenv-add-advice 'process-lines)
  (inheritenv-add-advice 'shell-command)
  (inheritenv-add-advice 'compile)

  ;; Elixir-specific commands that need environment inheritance
  (inheritenv-add-advice 'elixir-mix-test)
  (inheritenv-add-advice 'elixir-mix-compile)

  ;; ExUnit-specific advice (if using exunit.el)
  (when (featurep 'exunit)
    (inheritenv-add-advice 'exunit-run)
    (inheritenv-add-advice 'exunit-verify)
    (inheritenv-add-advice 'exunit-verify-single)
    (inheritenv-add-advice 'exunit-verify-all))

  ;; Add Apheleia commands to inherit environment
  (inheritenv-add-advice 'apheleia-format-buffer)
  (inheritenv-add-advice 'apheleia--run-formatter-process)
  (inheritenv-add-advice 'apheleia--format-region)
  
  ;; Also add general shell commands that Apheleia might use
  (inheritenv-add-advice 'start-process)
  (inheritenv-add-advice 'call-process)

  ;; Add advice for LSP if you're using elixir-ls
  ;; (when (featurep 'lsp-mode)
  ;;   (inheritenv-add-advice 'lsp)
  ;;   (inheritenv-add-advice 'lsp-restart-workspace))
  )

;; Ensure exunit gets the advice even if loaded later
(with-eval-after-load 'exunit
  (inheritenv-add-advice 'exunit-run)
  (inheritenv-add-advice 'exunit-verify)
  (inheritenv-add-advice 'exunit-verify-single)
  (inheritenv-add-advice 'exunit-verify-all))

(after! persp-mode
  ;; alternative, non-fancy version which only centers the output of +workspace--tabline
  (defun workspaces-formatted ()
    (+doom-dashboard--center (frame-width) (+workspace--tabline)))

  (defun hy/invisible-current-workspace ()
    "The tab bar doesn't update when only faces change (i.e. the
current workspace), so we invisibly print the current workspace
name as well to trigger updates"
    (propertize (safe-persp-name (get-current-persp)) 'invisible t))

  (customize-set-variable 'tab-bar-format '(workspaces-formatted tab-bar-format-align-right hy/invisible-current-workspace))

  ;; don't show current workspaces when we switch, since we always see them
  (advice-add #'+workspace/display :override #'ignore)
  ;; same for renaming and deleting (and saving, but oh well)
  (advice-add #'+workspace-message :override #'ignore))

;; need to run this later for it to not break frame size for some reason
(run-at-time nil nil (cmd! (tab-bar-mode +1)))

(custom-set-faces!
  '(+workspace-tab-face :inherit default :family "Jost" :height 135)
  '(+workspace-tab-selected-face :inherit (highlight +workspace-tab-face)))

(after! persp-mode
  (defun workspaces-formatted ()
    ;; fancy version as in screenshot
    (+doom-dashboard--center (frame-width)
        (let ((names (or persp-names-cache nil))
                (current-name (safe-persp-name (get-current-persp))))
        (mapconcat
        #'identity
        (cl-loop for name in names
                for i to (length names)
                collect
                (concat (propertize (format " %d" (1+ i)) 'face
                        `(:inherit ,(if (equal current-name name)
                                        '+workspace-tab-selected-face
                                        '+workspace-tab-face)
                        :weight bold))
                (propertize (format " %s " name) 'face
                        (if (equal current-name name)
                                '+workspace-tab-selected-face
                        '+workspace-tab-face))))
        " "))))
;; other persp-mode related configuration
)

;; Load startup profiling
(load! "startup-profiling")

(setq auth-sources '((:source "~/.authinfo")))
(setq gptel-log-level 'info)

(use-package! gptel)

;; Keybindings moved to consolidated section below

(gptel-make-anthropic "Claude"
  :stream t
  :key gptel-api-key)

(setq gptel-model 'claude-sonnet-4-20250514
  gptel-backend (gptel-make-anthropic "Claude"
                  :stream t
                  :key gptel-api-key)
  )
;; (setq gptel-model 'gpt-4-1106-preview
;;       gptel-backend (gptel-make-openai "OpenAI"
;;                      :key gptel-api-key  ;; Replace with your actual API key
;;                      :stream t
;;                      :models '(gpt-4-1106-preview)))
(after! gptel
  ;; Set a default system prompt that applies to all gptel interactions
  (setq gptel-directives
    '((default . "You are a helpful AI assistant with extensive programming knowledge, especially in Emacs Lisp. You provide concise, accurate responses and when appropriate, include runnable code examples. You use available tools to solve problems, including sequential thinking.")
       (creative . "You are a creative writing assistant who helps craft imaginative and engaging content. Be colorful and descriptive in your language.")
       (technical . "You are a technical documentation expert. Provide clear, precise explanations with examples when appropriate. Focus on accuracy and clarity.")
       (teacher . "You are a patient teacher explaining concepts in simple terms. Use analogies and break down complex ideas into understandable parts.")
       (debugger . "You are a debugging expert. Your job is to analyze code problems methodically, identify likely causes, and suggest specific fixes with explanations.")))

  ;; Set the default directive to use
  (setq gptel-system-prompt (alist-get 'default gptel-directives))

  ;; Ensure tools are enabled
  (setq gptel-use-tools t)
  (setq gptel-use-tools '(default all))

  ;; Always ask for confirmation before executing tool calls
  (setq gptel-confirm-tool-calls 'ask)

  (add-hook 'gptel-post-stream-hook 'gptel-auto-scroll)
  (add-hook 'gptel-post-response-functions 'gptel-auto-scroll)

  (setq gptel-add-prompt-confirmation nil)
  ;; Ask whether to include tool results in the response
  (setq gptel-include-tool-results 'ask)

;; Presets
(gptel-make-preset "nix-developer"
  :system "You are a nix developer, particularly tasked with packaging applications. You are careful, double checking packaging best-practices in each language you work with, and testing to make sure your packages always build. You are part of a pair, working with the user to form the best approach. You work incrementally, presenting the user with various alternatives and seeking feedback on design."
  :model 'claude-sonnet-4-20250514
  :temperature 0.1
  :tools (list
           ;; All web search (Nix tools not available in current setup)
           "search_duckduckgo" "read_url"
           ;; Sequential reasoning
           "sequentialthinking"
           ;; All filesystem
           "read_file" "write_file" "edit_file" "create_directory" "move_file" "get_file_info"
           "list_directory" "list_allowed_directories" "directory_tree" "search_files"
           "read_multiple_files" "zip_files" "unzip_file" "zip_directory"
           ;; All emacs mode
           "get_buffer_mode_info" "get_mode_documentation" "execute_mode_command"
           ;; All emacs repl
           "evaluate_elisp" "evaluate_elisp_in_buffer"
           ;; All user interaction
           "ask_user_question" "ask_user_choice" "notify_user" "confirm_user_action" "get_user_preference"))

(gptel-make-preset "emacs-llm-developer"
  :system "You are a developer helping to build llm tooling into emacs. Create tests for functionality, and examine the emacs state to ensure tools are working as we intend. You are part of a pair, and should ask the user for preferences, for help deciding between different approaches, and for feedback on designs."
  :model 'claude-sonnet-4-20250514
  :temperature 0.1
  :tools (list
           ;; All web search
           "search_duckduckgo" "read_url"
           ;; Sequential reasoning
           "sequentialthinking"
           ;; All filesystem
           "read_file" "write_file" "edit_file" "create_directory" "move_file" "get_file_info"
           "list_directory" "list_allowed_directories" "directory_tree" "search_files"
           "read_multiple_files" "zip_files" "unzip_file" "zip_directory"
           ;; All emacs mode
           "get_buffer_mode_info" "get_mode_documentation" "execute_mode_command"
           ;; All emacs repl
           "evaluate_elisp" "evaluate_elisp_in_buffer"
           ;; All user interaction
           "ask_user_question" "ask_user_choice" "notify_user" "confirm_user_action" "get_user_preference"))

(gptel-make-preset "software-developer"
  :system "You are a developer helping to build applications. You are part of a pair, and should ask the user for preferences, for help deciding between different approaches, and for feedback on designs."
  :model 'claude-sonnet-4-20250514
  :temperature 0.1
  :tools (list
           ;; All web search
           "search_duckduckgo" "read_url"
           ;; Sequential reasoning
           "sequentialthinking"
           ;; All filesystem
           "read_file" "write_file" "edit_file" "create_directory" "move_file" "get_file_info"
           "list_directory" "list_allowed_directories" "directory_tree" "search_files"
           "read_multiple_files" "zip_files" "unzip_file" "zip_directory"
           ;; All emacs mode
           "get_buffer_mode_info" "get_mode_documentation" "execute_mode_command"
           ;; All emacs repl
           "evaluate_elisp" "evaluate_elisp_in_buffer"
           ;; All user interaction
           "ask_user_question" "ask_user_choice" "notify_user" "confirm_user_action" "get_user_preference"))

(gptel-make-preset "product manager"
  :system "You are a product manager helping to plan software development. Research problem domains and available tools and libraries, and break down problems into a sequence of steps. Favor producing user stories and acceptance criteria rather than code"
  :model 'claude-sonnet-4-20250514
  :temperature 0.5
  :tools (list
           ;; All web search
           "search_duckduckgo" "read_url"
           ;; Sequential reasoning
           "sequentialthinking"
           ;; All filesystem
           "read_file" "write_file" "edit_file" "create_directory" "move_file" "get_file_info"
           "list_directory" "list_allowed_directories" "directory_tree" "search_files"
           "read_multiple_files" "zip_files" "unzip_file" "zip_directory"
           ;; All emacs mode
           "get_buffer_mode_info" "get_mode_documentation" "execute_mode_command"
           ;; All emacs repl
           "evaluate_elisp" "evaluate_elisp_in_buffer"
           ;; All user interaction
           "ask_user_question" "ask_user_choice" "notify_user" "confirm_user_action" "get_user_preference"))

)

(gptel-make-preset "executive assistant"
  :system "You are an executive assistant. You are very helpful, but unsure about your knowledge. When trying to do things, you rely on tools, and look things up online. You are aware that many websites are actually ads, so verify across several searches to make sure things are true. You always thing things through when trying to be of assistance. As an executive assistant, you confirm with the user before deciding a course of action"
  :model 'cluade-sonnet-4-20250514
  :temperature 0.6
  :tools (list
             ;; All web search
             "search_duckduckgo" "read_url"
             ;; Sequential reasoning
             "sequentialthinking"
             ;; All filesystem
             "read_file" "write_file" "edit_file" "create_directory" "move_file" "get_file_info"
             "list_directory" "list_allowed_directories" "directory_tree" "search_files"
             "read_multiple_files" "zip_files" "unzip_file" "zip_directory"
             "ask_user_question" "ask_user_choice" "notify_user" "confirm_user_action" "get_user_preference"))

;; Load the gptel tools file
(after! gptel
  (add-to-list 'load-path "~/.doom.d/gptel-tools")
  (load "~/.doom.d/gptel-tools/gptel-tools-index.el"))

(add-load-path! "mcp-hub")

(require 'mcp-hub)


(defvar mcp-search-root-directories
  (list (expand-file-name "~/")
        (expand-file-name "~/.doom.d/"))
  "List of root directories to search for git/jj repositories.")
(defvar mcp-filesystem-base-directories
  '(("zell" . ("/Users/zell/logseq/" "/Users/zell/git/" "/Users/zell/.doom.d"))
    ("coder" . ("/home/coder/.doom.d" "/home/coder/jj"))))

  (setq mcp-hub-servers
        `(("filesystem" . (:command "nix" :args ,(append '("run" "github:zgagnon/mcp-collection#filesystem")
                                                         (alist-get (user-login-name) mcp-filesystem-base-directories
                                                                    '("~/.doom.d") nil #'string=)
                                                         '("--" "-w"))))
          ("sequential-thinking" . (:command "npx" :args ("-y" "@modelcontextprotocol/server-sequential-thinking")))
          ("web-access" . (:command "nix" :args ("run" "github:zgagnon/mcp-collection#web-mcp") ))
          ("nix" . (:command "nix" :args ("run" "github:utensils/mcp-nixos", "--") ))
          ("text-editor" . (:command "uvx" :args ("mcp-text-editor")))
          ("user-interaction" . (:command "npx" :args ("-y" "interactive-mcp")))
          ("memory" . (:command "npx" :args ("-y" "@modelcontextprotocol/server-memory")))))

  ;; Don't start MCP servers automatically on startup
  ;; (add-hook 'after-init-hook
  ;;           #'mcp-hub-start-all-server)

  (defun gptel-mcp-register-tool ()
    (interactive)
    (let ((tools (mcp-hub-get-all-tool :asyncp t :categoryp t)))
      (mapcar #'(lambda (tool)
                  (apply #'gptel-make-tool
                         tool))
              tools)))

  (defun gptel-mcp-use-tool ()
    (interactive)
    (let ((tools (mcp-hub-get-all-tool :asyncp t :categoryp t)))
      (mapcar #'(lambda (tool)
                  (let ((path (list (plist-get tool :category)
                                    (plist-get tool :name))))
                    (push (gptel-get-tool path)
                          gptel-tools)))
              tools)))

  (defun gptel-mcp-close-use-tool ()
    (interactive)
    (let ((tools (mcp-hub-get-all-tool :asyncp t :categoryp t)))
      (mapcar #'(lambda (tool)
                  (let ((path (list (plist-get tool :category)
                                    (plist-get tool :name))))
                    (setq gptel-tools
                          (cl-remove-if #'(lambda (tool)
                                            (equal path
                                                   (list (gptel-tool-category tool)
                                                         (gptel-tool-name tool))))
                                        gptel-tools))))
              tools)))

  ;; MCP hub keybindings moved to consolidated section below

  (mcp-make-text-tool "filesystem" "write_file")

(use-package! claude-code-ide
  :bind ("C-c C-`" . claude-code-ide-menu)
  :config
  ;; Ensure Emacs can find claude CLI from Nix profile
  (add-to-list 'exec-path (expand-file-name "~/.nix-profile/bin"))
  
  ;; Basic configuration - start minimal to debug
  (setq claude-code-ide-cli-path (or (executable-find "claude")
                                     (expand-file-name "~/.nix-profile/bin/claude"))
        claude-code-ide-terminal-backend 'eat
        claude-code-ide-window-side 'right
        claude-code-ide-window-width 100)
  
  ;; Enable built-in Emacs MCP tools after basic setup
  (claude-code-ide-emacs-tools-setup)

  ;; Add additional MCP tools configuration
  (setq claude-code-ide-mcp-tools
        '(;; Built-in Emacs navigation tools
          "xref-find-references"
          "xref-find-apropos" 
          "treesit-info"
          "imenu-list-symbols"
          "project-info"
          ;; Custom tools (uncomment and add as needed)
          ;; "custom-function-name"
          ))

  (setq claude-code-ide-buffer-name-function
    (lambda (directory)
      (if directory
        (format "*Claude-Code:%s*"
          (file-name-nondirectory (directory-file-name directory)))
        "*Claude-Code:Global*")))

  ;; Nix develop integration for claude-code-ide
  ;; This ensures claude-code-ide runs in nix develop environments when available
  (defun claude-code-ide--with-nix-develop (orig-fun &rest args)
    "Advice to run claude-code-ide commands in nix develop environment when available."
    (let* ((current-dir default-directory)
           (wrapper-script (expand-file-name "~/.doom.d/nix-adapters/claude-code-nix-wrapper.sh"))
           (flake-dir (claude-code-ide--find-flake-dir current-dir)))
      (if (and (file-exists-p wrapper-script) flake-dir)
          (let ((default-directory flake-dir))
            (apply orig-fun args))
        (apply orig-fun args))))

  (defun claude-code-ide--find-flake-dir (dir)
    "Find the nearest directory containing a flake.nix file."
    (let ((current-dir (expand-file-name dir)))
      (while (and current-dir
                  (not (string= current-dir "/"))
                  (not (file-exists-p (expand-file-name "flake.nix" current-dir))))
        (setq current-dir (file-name-directory (directory-file-name current-dir))))
      (when (and current-dir (file-exists-p (expand-file-name "flake.nix" current-dir)))
        current-dir)))

  ;; Add advice to ensure claude-code-ide commands run in nix develop context
  (advice-add 'claude-code-ide :around #'claude-code-ide--with-nix-develop)
  
  ;; Also modify the shell command to use our wrapper
  (defun claude-code-ide--get-wrapped-shell ()
    "Get shell command wrapped for nix develop environment."
    (let ((wrapper-script (expand-file-name "~/.doom.d/nix-adapters/claude-code-nix-wrapper.sh")))
      (if (file-exists-p wrapper-script)
          (list wrapper-script shell-file-name)
        (list shell-file-name))))

  ;; Set the shell command for claude-code-ide to use our wrapper
  (setq claude-code-ide-shell-command-function #'claude-code-ide--get-wrapped-shell)

  ;; Claude Code IDE keybindings moved to consolidated section below
  )

;; Consolidated keybindings for all robot chat functionality
;; This prevents conflicts between multiple map! calls with the same prefix
(after! gptel
  (map! :leader
        (:prefix ("r" . "robot chat")
         ;; GPTel commands (direct under r)
         :desc "Send the contents of the buffer up to point" "s" #'gptel-send
         :desc "Open a new chat buffer" "o" #'gptel
         :desc "Open gptel menu" "m" #'gptel-menu
         :desc "Add a region or buffer to the chat context" "a" #'gptel-add
         :desc "Add a file to the chat context" "f" #'gptel-add-file
         :desc "Rewrite selected region" "r" #'gptel-rewrite
         :desc "Limit to org mode topic" "t" #'gptel-org-set-topic
         :desc "Send escape to Claude Code IDE" "<escape>" #'claude-code-ide-send-escape

         ;; MCP Hub commands under r p
         (:prefix ("p" . "MCP Hub")
          :desc "Open MCP Hub" "h" #'mcp-hub
          :desc "Register MCP tools with GPTel" "g" #'gptel-mcp-register-tool
          :desc "Show logs for MCP server" "l" #'mcp-hub-view-log
          :desc "Restart MCP server" "r" #'mcp-hub-restart-server)
         
         ;; Claude Code IDE commands under r c
         (:prefix ("c" . "claude code")
          :desc "Claude Code menu" "m" #'claude-code-ide-menu
          :desc "Start Claude Code" "s" #'claude-code-ide
          :desc "Send prompt" "p" #'claude-code-ide-send-prompt
          :desc "Continue conversation" "c" #'claude-code-ide-continue
          :desc "Resume session" "r" #'claude-code-ide-resume
          :desc "Stop Claude Code" "q" #'claude-code-ide-stop
          :desc "Switch to buffer" "b" #'claude-code-ide-switch-to-buffer
          :desc "List sessions" "l" #'claude-code-ide-list-sessions
          :desc "Toggle window" "t" #'claude-code-ide-toggle
          :desc "Send selection" "@" #'claude-code-ide-insert-at-mentioned))))

(setq user-full-name "Zoe Gagnon"
      user-mail-address "zoe@zgagnon.com")

(after! eat
  ;; Enable yank to terminal for clipboard paste functionality
  (setq eat-enable-yank-to-terminal t)
  ;; Enable kill from terminal to add killed text to Emacs kill ring
  (setq eat-enable-kill-from-terminal t)
  
  (map! :leader
        (:prefix ("e" . "eat terminal")
         :desc "Reload eat terminal" "r" #'eat-reload
         :desc "Reset eat terminal" "t" #'eat-reset)))

(setq read-process-output-max (* 1024 1024))
(setq gc-cons-threshold 100000000)
(setq lsp-idle-delay 0.5)

(defvar my/global-lsp-ignore-dirs
  '("_build" "deps" ".jj" ".direnv" "node_modules" "result" "target"))

(defun make-lsp-ignore-patterns (patterns)
  (mapcar (lambda (pattern) (format "**/%s/**" pattern)) patterns))

(after! lsp-mode
  (setq lsp-file-watch-ignored-directories
    (append lsp-file-watch-ignored-directories
      (make-lsp-ignore-patterns my/global-lsp-ignore-dirs))))

(use-package! treesit-auto
  :custom
  (treesit-auto-install 'prompt)
  :config
  (treesit-auto-add-to-auto-mode-alist 'all)
  (global-treesit-auto-mode))

;; Make sure direnv loads properly with Elixir

(after! lsp-mode
  (add-hook 'elixir-ts-mode-hook #'lsp))

(after! elixir-ts-mode
  (add-hook 'elixir-ts-mode-hook #'lsp)  ; Activate LSP when elixir-ts-mode is active
  (map! :map elixir-ts-mode-map
        :leader
        (:prefix ("m t" . "Exunit tests")
         :desc "Verify single ExUnit test" "s" #'exunit-verify-single
         :desc "Verify all ExUnit tests" "a" #'exunit-verify-all
         :desc "Verify all tests in the umbrella project" "u" #'exunit-verify-all-in-umbrella
         :desc "Run all tests in this buffer" "v" #'exunit-verify
         :desc "Rerun the last test invocation" "r" #'exunit-rerun
         :desc "Rerun the last test with debugging" "d" #'exunit-debug
         :desc "Toggle between file and test" "t" #'exunit-toggle-file-and-test
         )))

;; Enable envrc globally to handle direnv automatically
(after! envrc
  (envrc-global-mode +1))

;; Track which projects have already been loaded to avoid repeated loads
(defvar my/envrc-loaded-projects nil
  "List of project directories where envrc has already been loaded.")

(defun my/ensure-envrc-loaded-once ()
  "Ensure envrc is loaded once per project for Elixir files."
  (when (and (buffer-file-name)
             (string-match-p "\\.exs?$" (buffer-file-name)))
    (let* ((project-root (locate-dominating-file (buffer-file-name) ".envrc"))
           (project-root (when project-root (expand-file-name project-root))))
      (when (and project-root
                 (not (member project-root my/envrc-loaded-projects)))
        (let ((default-directory project-root))
          (envrc-allow)
          (envrc-reload)
          (push project-root my/envrc-loaded-projects)
          (message "Loaded direnv for project: %s" project-root))))))

;; Only hook to elixir-ts-mode, not find-file-hook
(add-hook 'elixir-ts-mode-hook #'my/ensure-envrc-loaded-once)

;; Universal Elixir-LS Environment Integration
;; This configures LSP to use a universal wrapper script that automatically
;; detects and activates the appropriate development environment:
;; The wrapper script (~/.doom.d/nix-adapters/elixir-ls-universal-wrapper.sh) handles:
;; - Nix flake detection and 'nix develop' activation (priority 1)
;; - Direnv detection and 'direnv exec' activation (priority 2)  
;; - Fallback to global elixir-ls for projects without environment management
;; This eliminates the need for per-project .dir-locals.el configuration.
(after! lsp-mode
  (lsp-register-client
   (make-lsp-client
    :new-connection (lsp-stdio-connection
                     (lambda ()
                       (list (expand-file-name "~/.doom.d/nix-adapters/elixir-ls-universal-wrapper.sh"))))
    :major-modes '(elixir-mode elixir-ts-mode)
    :priority 1
    :server-id 'elixir-ls-universal
    :initialization-options (lambda () (list :dialyzerEnabled :json-false)))))

(setq treesit-language-source-alist
      (append treesit-language-source-alist
              '((rust "https://github.com/tree-sitter/tree-sitter-rust"))))

(add-to-list 'major-mode-remap-alist '(rust-mode . rust-ts-mode))

(use-package! lsp-tailwindcss)

(load! "lisp-formatting")

;; Place your private configuration here! Remember, you do not need to run 'doom
;; sync' after modifying this file!


;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets. It is optional.
;; (setq user-full-name "John Doe"
;;       user-mail-address "john@doe.com")

;; Doom exposes five (optional) variables for controlling fonts in Doom:
;;
;; - `doom-font' -- the primary font to use
;; - `doom-variable-pitch-font' -- a non-monospace font (where applicable)
;; - `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;; - `doom-symbol-font' -- for symbols
;; - `doom-serif-font' -- for the `fixed-pitch-serif' face
;;
;; See 'C-h v doom-font' for documentation and more examples of what they
;; accept. For example:
;;
;;(setq doom-font (font-spec :family "Fira Code" :size 12 :weight 'semi-light)
;;      doom-variable-pitch-font (font-spec :family "Fira Sans" :size 13))
;;
;; If you or Emacs can't find your font, use 'M-x describe-font' to look them
;; up, `M-x eval-region' to execute elisp code, and 'M-x doom/reload-font' to
;; refresh your font settings. If Emacs still can't find your font, it likely
;; wasn't installed correctly. Font issues are rarely Doom issues!

;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:
(setq doom-theme 'catppuccin)

;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
(setq display-line-numbers-type t)

;; If you use `org' and don't want your org files in the default location below,
;; change `org-directory'. It must be set before org loads!
(setq org-directory "~/org/")


;; Whenever you reconfigure a package, make sure to wrap your config in an
;; `after!' block, otherwise Doom's defaults may override your settings. E.g.
;;
;;   (after! PACKAGE
;;     (setq x y))
;;
;; The exceptions to this rule:
;;
;;   - Setting file/directory variables (like `org-directory')
;;   - Setting variables which explicitly tell you to set them before their
;;     package is loaded (see 'C-h v VARIABLE' to look up their documentation).
;;   - Setting doom variables (which start with 'doom-' or '+').
;;
;; Here are some additional functions/macros that will help you configure Doom.
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;; Alternatively, use `C-h o' to look up a symbol (functions, variables, faces,
;; etc).
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.
