;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
;; This file is auto generated. Do not edit this file. All changes must be made in config.org

(setq doom-font (font-spec :family "FiraCode Nerd Font" :size 18 :weight 'medium)
     doom-variable-pitch-font (font-spec :family "FiraCode Nerd Font" :size 18)
      doom-symbol-font (font-spec :family "FiraCode Nerd Font" :size 18)
      doom-serif-font (font-spec :family "FiraCode Nerd Font" :size 18))

(setq org-directory "~/org/")


(custom-set-faces!
  `(org-level-1 :family "Luminari" :height 400)
  `(org-level-2 :family "Cochin" :height 300)
  `(org-level-3 :family "Rockwell" :height 200)
  `(org-level-4 :family "Rockwell" :height 150)
  `(org-level-5 :family "Rockwell" :height 150)
  `(org-level-6 :family "Rockwell" :height 150)
                )

(setq projectile-enable-caching nil)

(setq catppuccin-flavor 'latte)

(setq display-line-numbers-type t)
(setq-default tab-width 2)
(global-visual-line-mode 1)
(if (display-graphic-p)
    (progn
      (setq initial-frame-alist
            '((tool-bar-lines . 0)
              (width . 200)
              (height . 400)
              )
            )
      )
  )

(add-function :after after-focus-change-function
  (lambda ()
    (save-some-buffers t)))

(setq undo-limit 80000000
      evil-want-fine-undo t
      auto-save-default t)

(global-subword-mode t)

(after! evil
  (setq evil-kill-on-visual-paste t))

(after! persp-mode
  ;; alternative, non-fancy version which only centers the output of +workspace--tabline
  (defun workspaces-formatted ()
    (+doom-dashboard--center (frame-width) (+workspace--tabline)))

  (defun hy/invisible-current-workspace ()
    "The tab bar doesn't update when only faces change (i.e. the
current workspace), so we invisibly print the current workspace
name as well to trigger updates"
    (propertize (safe-persp-name (get-current-persp)) 'invisible t))

  (customize-set-variable 'tab-bar-format '(workspaces-formatted tab-bar-format-align-right hy/invisible-current-workspace))

  ;; don't show current workspaces when we switch, since we always see them
  (advice-add #'+workspace/display :override #'ignore)
  ;; same for renaming and deleting (and saving, but oh well)
  (advice-add #'+workspace-message :override #'ignore))

;; need to run this later for it to not break frame size for some reason
(run-at-time nil nil (cmd! (tab-bar-mode +1)))

(custom-set-faces!
  '(+workspace-tab-face :inherit default :family "Jost" :height 135)
  '(+workspace-tab-selected-face :inherit (highlight +workspace-tab-face)))

(after! persp-mode
  (defun workspaces-formatted ()
    ;; fancy version as in screenshot
    (+doom-dashboard--center (frame-width)
        (let ((names (or persp-names-cache nil))
                (current-name (safe-persp-name (get-current-persp))))
        (mapconcat
        #'identity
        (cl-loop for name in names
                for i to (length names)
                collect
                (concat (propertize (format " %d" (1+ i)) 'face
                        `(:inherit ,(if (equal current-name name)
                                        '+workspace-tab-selected-face
                                        '+workspace-tab-face)
                        :weight bold))
                (propertize (format " %s " name) 'face
                        (if (equal current-name name)
                                '+workspace-tab-selected-face
                        '+workspace-tab-face))))
        " "))))
;; other persp-mode related configuration
)

(setq auth-sources '((:source "~/.authinfo")))

(use-package! gptel)

(after! gptel
  (map! :leader
        (:prefix ("r" . "robot chat")
         :desc  "Send the contents of the buffer up to point" "s"#'gptel-send
         :desc  "Open a new chat buffer" "o" #'gptel
         :desc "Open gptel menu" "m"  #'gptel-menu
         :desc  "Add a region or buffer to the chat context" "a" #'gptel-add
         :desc  "Add a file to the chat context" "f" #'gptel-add-file
         :desc "Rewrite selected region" "r" #'gptel-rewrite
         :desc "Limit to org mode topic" "t"  #'gptel-org-set-topic)))

(gptel-make-anthropic "Claude"
  :stream t
  :key gptel-api-key)

(setq gptel-model 'claude-3-7-sonnet-20250219
      gptel-backend (gptel-make-anthropic "Claude"
                      :stream t
                      :key gptel-api-key)
      )
;; (setq gptel-model 'gpt-4-1106-preview
;;       gptel-backend (gptel-make-openai "OpenAI"
;;                      :key gptel-api-key  ;; Replace with your actual API key
;;                      :stream t
;;                      :models '(gpt-4-1106-preview)))
(after! gptel
  ;; Set a default system prompt that applies to all gptel interactions
  (setq gptel-directives
        '((default . "You are a helpful AI assistant with extensive programming knowledge, especially in Emacs Lisp. You provide concise, accurate responses and when appropriate, include runnable code examples. You use available tools to solve problems, including sequential thinking.")
          (creative . "You are a creative writing assistant who helps craft imaginative and engaging content. Be colorful and descriptive in your language.")
          (technical . "You are a technical documentation expert. Provide clear, precise explanations with examples when appropriate. Focus on accuracy and clarity.")
          (teacher . "You are a patient teacher explaining concepts in simple terms. Use analogies and break down complex ideas into understandable parts.")
          (debugger . "You are a debugging expert. Your job is to analyze code problems methodically, identify likely causes, and suggest specific fixes with explanations.")))

  ;; Set the default directive to use
  (setq gptel-system-prompt (alist-get 'default gptel-directives))

  ;; Ensure tools are enabled
  (setq gptel-use-tools t)
  (setq gptel-use-tools '(default all))

  ;; Always ask for confirmation before executing tool calls
  (setq gptel-confirm-tool-calls 'ask)

  (setq gptel-add-prompt-confirmation nil)
  ;; Ask whether to include tool results in the response
  (setq gptel-include-tool-results 'ask))

;; Load the gptel tools file
(after! gptel
  (add-to-list 'load-path "~/.doom.d/gptel-tools")
  (load "~/.doom.d/gptel-tools/gptel-tools-index.el"))

(add-load-path! "mcp-hub")

(require 'mcp-hub)

(defvar mcp-search-root-directories
  (list (expand-file-name "~/")
        (expand-file-name "~/.doom.d/"))
  "List of root directories to search for git/jj repositories.")

(defun mcp-discover-projects ()
  "Return a list of directories containing git/jj repositories using fd."
  (let ((project-dirs '())
        (excluded-dirs '(".Trash" ".cache" "Library" ".local" "Applications" "Music" "Movies" "Pictures")))

    ;; Search through each specified root directory
    (dolist (root-dir mcp-search-root-directories)
      (when (file-directory-p root-dir)
        ;; Check if the root itself is a git/jj repo
        (if (or (file-exists-p (expand-file-name ".git" root-dir))
                (file-exists-p (expand-file-name ".jj" root-dir)))
            (push root-dir project-dirs))

        ;; Search for all non-excluded directories under this root
        (dolist (dir (directory-files root-dir t))
          (when (and (file-directory-p dir)
                     (not (member (file-name-nondirectory dir) excluded-dirs))
                     (not (string-match-p "/\\." (file-name-directory dir))))
            ;; Check if this is a git/jj repo
            (if (or (file-exists-p (expand-file-name ".git" dir))
                    (file-exists-p (expand-file-name ".jj" dir)))
                (push dir project-dirs)
              ;; Use fd to find repositories in this directory
              (when-let* ((default-directory dir)
                          (fd-available (executable-find "fd"))
                          (cmd (concat "fd -H -t d -E .Trash -E node_modules -E .cargo "
                                      "'^\\.(git|jj)$' --max-depth 4 -x dirname {} | xargs realpath"))
                          (repos (ignore-errors
                                   (split-string (shell-command-to-string cmd) "\n" t))))
                (setq project-dirs (append repos project-dirs))))))))

    ;; Make sure all paths are absolute
    (mapcar #'expand-file-name project-dirs)))

(setq mcp-hub-servers
  `(("filesystem" . (:command "npx" :args ("-y" "@modelcontextprotocol/server-filesystem"
                                          ,@(mcp-discover-projects))))
     ("sequential-thinking" . (:command "npx" :args ("-y" "@modelcontextprotocol/server-sequential-thinking")))
     ("web-access" . (:command "npx" :args ("-y" "github:zgagnon/web-mcp") ))
     ("text-editor" . (:command "uvx" :args ("mcp-text-editor")))
     ("memory" . (:command "npx" :args ("-y" "@modelcontextprotocol/server-memory")))))

(add-hook 'after-init-hook
  #'mcp-hub-start-all-server)

(defun gptel-mcp-register-tool ()
  (interactive)
  (let ((tools (mcp-hub-get-all-tool :asyncp t :categoryp t)))
    (mapcar #'(lambda (tool)
                (apply #'gptel-make-tool
                  tool))
      tools)))

(defun gptel-mcp-use-tool ()
  (interactive)
  (let ((tools (mcp-hub-get-all-tool :asyncp t :categoryp t)))
    (mapcar #'(lambda (tool)
                (let ((path (list (plist-get tool :category)
                              (plist-get tool :name))))
                  (push (gptel-get-tool path)
                    gptel-tools)))
      tools)))

(defun gptel-mcp-close-use-tool ()
  (interactive)
  (let ((tools (mcp-hub-get-all-tool :asyncp t :categoryp t)))
    (mapcar #'(lambda (tool)
                (let ((path (list (plist-get tool :category)
                              (plist-get tool :name))))
                  (setq gptel-tools
                    (cl-remove-if #'(lambda (tool)
                                      (equal path
                                        (list (gptel-tool-category tool)
                                          (gptel-tool-name tool))))
                      gptel-tools))))
      tools)))

;; Add MCP hub keybindings under leader r p
(map! :leader
  (:prefix ("r" . "robot chat")
    (:prefix ("p" . "MCP Hub")
      :desc "Open MCP Hub" "h" #'mcp-hub
      :desc "Register MCP tools with GPTel" "g" #'gptel-mcp-register-tool
      :desc "Show logs for MCP server" "l" #'mcp-hub-view-log
      :desc "Restart MCP server" "r" #'mcp-hub-restart-server)))

(mcp-make-text-tool "filesystem" "write_file")

(use-package aider
  :config
  (setq aider-args '("--model" "gpt-4o-mini")))

(setq user-full-name "Zoe Gagnon"
      user-mail-address "zoe@zgagnon.com")

(setq read-process-output-max (* 1024 1024))
(setq gc-cons-threshold 100000000)
(setq lsp-idle-delay 0.5)

(use-package! treesit-auto
  :custom
  (treesit-auto-install 'prompt)
  :config
  (treesit-auto-add-to-auto-mode-alist 'all)
  (global-treesit-auto-mode))

;; Make sure direnv loads properly with Elixir

(after! lsp-mode
  (add-hook 'elixir-ts-mode-hook #'lsp))

(after! elixir-ts-mode
  (add-hook 'elixir-ts-mode-hook #'lsp)  ; Activate LSP when elixir-ts-mode is active
  (map! :map elixir-ts-mode-map
        :leader
        (:prefix ("m t" . "Exunit tests")
         :desc "Verify single ExUnit test" "s" #'exunit-verify-single
         :desc "Verify all ExUnit tests" "a" #'exunit-verify-all
         :desc "Verify all tests in the umbrella project" "u" #'exunit-verify-all-in-umbrella
         :desc "Run all tests in this buffer" "v" #'exunit-verify
         :desc "Rerun the last test invocation" "r" #'exunit-rerun
         :desc "Rerun the last test with debugging" "d" #'exunit-debug
         :desc "Toggle between file and test" "t" #'exunit-toggle-file-and-test
         )))

(setq treesit-language-source-alist
      (append treesit-language-source-alist
              '((rust "https://github.com/tree-sitter/tree-sitter-rust"))))

(add-to-list 'major-mode-remap-alist '(rust-mode . rust-ts-mode))

(use-package! lsp-tailwindcss)

(load! "lisp-formatting")

;; Place your private configuration here! Remember, you do not need to run 'doom
;; sync' after modifying this file!


;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets. It is optional.
;; (setq user-full-name "John Doe"
;;       user-mail-address "john@doe.com")

;; Doom exposes five (optional) variables for controlling fonts in Doom:
;;
;; - `doom-font' -- the primary font to use
;; - `doom-variable-pitch-font' -- a non-monospace font (where applicable)
;; - `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;; - `doom-symbol-font' -- for symbols
;; - `doom-serif-font' -- for the `fixed-pitch-serif' face
;;
;; See 'C-h v doom-font' for documentation and more examples of what they
;; accept. For example:
;;
;;(setq doom-font (font-spec :family "Fira Code" :size 12 :weight 'semi-light)
;;      doom-variable-pitch-font (font-spec :family "Fira Sans" :size 13))
;;
;; If you or Emacs can't find your font, use 'M-x describe-font' to look them
;; up, `M-x eval-region' to execute elisp code, and 'M-x doom/reload-font' to
;; refresh your font settings. If Emacs still can't find your font, it likely
;; wasn't installed correctly. Font issues are rarely Doom issues!

;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:
(setq doom-theme 'catppuccin)

;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
(setq display-line-numbers-type t)

;; If you use `org' and don't want your org files in the default location below,
;; change `org-directory'. It must be set before org loads!
(setq org-directory "~/org/")


;; Whenever you reconfigure a package, make sure to wrap your config in an
;; `after!' block, otherwise Doom's defaults may override your settings. E.g.
;;
;;   (after! PACKAGE
;;     (setq x y))
;;
;; The exceptions to this rule:
;;
;;   - Setting file/directory variables (like `org-directory')
;;   - Setting variables which explicitly tell you to set them before their
;;     package is loaded (see 'C-h v VARIABLE' to look up their documentation).
;;   - Setting doom variables (which start with 'doom-' or '+').
;;
;; Here are some additional functions/macros that will help you configure Doom.
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;; Alternatively, use `C-h o' to look up a symbol (functions, variables, faces,
;; etc).
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.
